export const ADMIN_GETALLEMPLOYEE_SUCCESS = "ADMIN_GETALLEMPLOYEE_SUCCESS";
export const ADMIN_GETALLEMPLOYEE_FAILED = "ADMIN_GETALLEMPLOYEE_FAILED";
export const ADMIN_GETALLEMPLOYEE_REQUEST = "ADMIN_GETALLEMPLOYEE_REQUEST";

export const ADMIN_GETALLTEAMS_REQUEST = "ADMIN_GETALLTEAMS_REQUEST";
export const ADMIN_GETALLTEAMS_SUCCESS = "ADMIN_GETALLTEAMS_SUCCESS";
export const ADMIN_GETALLTEAMS_FAILED = "ADMIN_GETALLTEAMS_FAILED";

export const ADMIN_GETALLCLIENTS_REQUEST = "ADMIN_GETALLCLIENTS_REQUEST";
export const ADMIN_GETALLCLIENTS_SUCCESS = "ADMIN_GETALLCLIENTS_SUCCESS";
export const ADMIN_GETALLCLIENTS_FAILED = "ADMIN_GETALLCLIENTS_FAILED";

export const ADMIN_GETALLPROJECTS_REQUEST = "ADMIN_GETALLPROJECTS_REQUEST";
export const ADMIN_GETALLPROJECTS_SUCCESS = "ADMIN_GETALLPROJECTS_SUCCESS";
export const ADMIN_GETALLPROJECTS_FAILED = "ADMIN_GETALLPROJECTS_FAILED";
