export const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAILED = "GET_CLIENT_FAILED";

export const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAILED = "ADD_CLIENT_FAILED";
export const ADD_CLIENT_RESET = "ADD_CLIENT_RESET";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";
export const DELETE_CLIENT_RESET = "DELETE_CLIENT_RESET";

export const GET_CLIENTPRO_RESET = "GET_CLIENTPRO_RESET";
export const GET_CLIENTPRO_SUCCESS = "GET_CLIENTPRO_SUCCESS";
export const GET_CLIENTPRO_FAILED = "GET_CLIENTPRO_FAILED";
export const GET_CLIENTPRO_REQUEST = "GET_CLIENTPRO_REQUEST";
