export const GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAILED = 'GET_CLIENT_FAILED';

export const CLIENT_PROJECTS_REQUEST = 'CLIENT_PROJECTS_REQUEST';
export const CLIENT_PROJECTS_SUCCESS = 'CLIENT_PROJECTS_SUCCESS';
export const CLIENT_PROJECTS_FAILED = 'CLIENT_PROJECTS_FAILED';
