export const GET_ALLEMPLOYEES_REQUEST = "GET_ALLEMPLOYEES_REQUEST";
export const GET_ALLEMPLOYEES_SUCCESS = "GET_ALLEMPLOYEES_SUCCESS";
export const GET_ALLEMPLOYEES_FAILED = "GET_ALLEMPLOYEES_FAILED";
