export const GET_COMMONDATA_SUCCESS = "GET_COMMONDATA_SUCCESS";
export const GET_COMMONDATA_FAILED = "GET_COMMONDATA_FAILED";
export const DELETE_SS_SUCCESS = "DELETE_SS_SUCCESS";
export const DELETE_SS_FAILED = "DELETE_SS_FAILED";
export const DELETE_ACT_SUCCESS = "DELETE_ACT_SUCCESS";
export const DELETE_ACT_FAILED = "DELETE_ACT_FAILED";
