export const GET_COMMONDATA_SUCCESS = "GET_COMMONDATA_SUCCESS";
export const GET_COMMONDATA_FAILED = "GET_COMMONDATA_FAILED";
export const DELETE_SS_SUCCESS = "DELETE_SS_SUCCESS";
export const DELETE_SS_FAILED = "DELETE_SS_FAILED";
export const DELETE_ACT_SUCCESS = "DELETE_ACT_SUCCESS";
export const DELETE_ACT_FAILED = "DELETE_ACT_FAILED";

// export const GET_EMPLOYEEDATA_SUCCESS = "GET_EMPLOYEEDATA_SUCCESS";
// export const GET_EMPLOYEEDATA_FAILED = "GET_EMPLOYEEDATA_FAILED";
export const EMP_DELETE_SS_SUCCESS = "EMP_DELETE_SS_SUCCESS";
export const EMP_DELETE_SS_FAILED = "EMP_DELETE_SS_FAILED";
export const EMP_DELETE_ACT_SUCCESS = "EMP_DELETE_ACT_SUCCESS";
export const EMP_DELETE_ACT_FAILED = "EMP_DELETE_ACT_FAILED";

export const TEAM_COMMONDATA_SUCCESS = "TEAM_COMMONDATA_SUCCESS";
export const TEAM_COMMONDATA_FAILED = "TEAM_COMMONDATA_FAILED";

export const PROJECTMEMBER_CD_SUCCESS = "PROJECTMEMBER_CD_SUCCESS";
export const PROJECTMEMBER_CD_FAILED = "PROJECTMEMBER_CD_FAILED";
