export const EMPLOYEE_DETAILS_REQUEST = "EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAILED = "EMPLOYEE_DETAILS_FAILED";
export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAILED = "EMPLOYEE_UPDATE_FAILED";

export const GET_EMPLOYEEDATA_SUCCESS = "GET_EMPLOYEEDATA_SUCCESS";
export const GET_EMPLOYEEDATA_FAILED = "GET_EMPLOYEEDATA_FAILED";
