export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';

export const CREATE_PROJECTS_REQUEST = 'CREATE_PROJECTS_REQUEST';
export const CREATE_PROJECTS_SUCCESS = 'CREATE_PROJECTS_SUCCESS';
export const CREATE_PROJECTS_FAILED = 'CREATE_PROJECTS_FAILED';
export const CREATE_PROJECTS_RESET = 'CREATE_PROJECTS_RESET';

export const ADD_TEAM_PROJECTS_REQUEST = 'ADD_TEAM_PROJECTS_REQUEST';
export const ADD_TEAM_PROJECTS_SUCCESS = 'ADD_TEAM_PROJECTS_SUCCESS';
export const ADD_TEAM_PROJECTS_FAILED = 'ADD_TEAM_PROJECTS_FAILED';
export const ADD_TEAM_PROJECTS_RESET = 'ADD_TEAM_PROJECTS_RESET';
