export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED";

export const CREATE_PROJECTS_REQUEST = "CREATE_PROJECTS_REQUEST";
export const CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS";
export const CREATE_PROJECTS_FAILED = "CREATE_PROJECTS_FAILED";
export const CREATE_PROJECTS_RESET = "CREATE_PROJECTS_RESET";

export const ADD_TEAM_PROJECTS_REQUEST = "ADD_TEAM_PROJECTS_REQUEST";
export const ADD_TEAM_PROJECTS_SUCCESS = "ADD_TEAM_PROJECTS_SUCCESS";
export const ADD_TEAM_PROJECTS_FAILED = "ADD_TEAM_PROJECTS_FAILED";
export const ADD_TEAM_PROJECTS_RESET = "ADD_TEAM_PROJECTS_RESET";

export const EDIT_PROJECTS_REQUEST = "EDIT_PROJECTS_REQUEST";
export const EDIT_PROJECTS_SUCCESS = "EDIT_PROJECTS_SUCCESS";
export const EDIT_PROJECTS_FAILED = "EDIT_PROJECTS_FAILED";
export const EDIT_PROJECTS_RESET = "EDIT_PROJECTS_RESET";

export const DELETE_PROJECTS_REQUEST = "DELETE_PROJECTS_REQUEST";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_FAILED = "DELETE_PROJECTS_FAILED";
export const DELETE_PROJECTS_RESET = "DELETE_PROJECTS_RESET";

export const GET_PROJECT_BYID_REQUEST = "GET_PROJECT_BYID_REQUEST";
export const GET_PROJECT_BYID_SUCCESS = "GET_PROJECT_BYID_SUCCESS";
export const GET_PROJECT_BYID_FAILED = "GET_PROJECT_BYID_FAILED";
export const GET_PROJECT_BYID_RESET = "GET_PROJECT_BYID_RESET";

export const ADD_MEMBER_TOPROJECT_SUCCESS = "ADD_MEMBER_TOPROJECT_SUCCESS";
export const ADD_MEMBER_TOPROJECT_FAILED = "ADD_MEMBER_TOPROJECT_FAILED";
export const ADD_MEMBER_TOPROJECT_RESET = "ADD_MEMBER_TOPROJECT_RESET";

export const ADD_PROJECTLEADER_SUCCESS = "ADD_PROJECTLEADER_SUCCESS";
export const ADD_PROJECTLEADER_FAILED = "ADD_PROJECTLEADER_FAILED";
export const ADD_PROJECTLEADER_RESET = "ADD_PROJECTLEADER_RESET";

export const REMOVE_MEMBER_FROMRPOJECT_SUCCESS =
  " REMOVE_MEMBER_FROMRPOJECT_SUCCESS";
export const REMOVE_MEMBER_FROMRPOJECT_FAILED =
  " REMOVE_MEMBER_FROMRPOJECT_FAILED";
export const REMOVE_MEMBER_FROMRPOJECT_RESET =
  " REMOVE_MEMBER_FROMRPOJECT_RESET";

export const EDIT_PROJECTLEADER_SUCCESS = "EDIT_PROJECTLEADER_SUCCESS";
export const EDIT_PROJECTLEADER_FAILED = "EDIT_PROJECTLEADER_FAILED";
export const EDIT_PROJECTLEADER_RESET = "EDIT_PROJECTLEADER_RESET";
