export const TEAM_CREATE_REQUEST = 'TEAM_CREATE_REQUEST';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAILED = 'TEAM_CREATE_FAILED';
export const TEAM_CREATE_RESET = 'TEAM_CREATE_RESET';

export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE';
export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST';
