export const TEAM_CREATE_REQUEST = 'TEAM_CREATE_REQUEST';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAILED = 'TEAM_CREATE_FAILED';
export const TEAM_CREATE_RESET = 'TEAM_CREATE_RESET';

export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS';
export const EMPLOYEE_LIST_FAILED = 'EMPLOYEE_LIST_FAILED';
