swagger: '2.0'
info:
  title: 'ScreenShot Monitoring API'
  description: 'Screenshot monitoring application - Meru Accounting'
  contact:
    email: harnish@gmail.com
  servers:
    -url: 'http://localhost:8000'
    description: This is my local server
    -url: 'https://meruserver.com/'
    description: This is company server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      in: header
      bearerFormat: JWT
  security: [bearerAuth]

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

schemes: [http]


tags: 
  name: Auth
  description: Login, Register and CommonData Routes

paths:
#############################################
  /commondata:
    get:
      summary: Returns common data
      description: Get common data related of user logged in
      tags: [Auth]
      security:
        -bearerAuth: []
      responses: 
        200:
          description: Success
          schema:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
        401:
          $ref: "#/components/responses/UnauthorizedError"
############################################
  /register:
    post:
      summary: Register a user
      description: Register a new user
      tags: [Auth]
      responses: 
        200:
         description: Success
          schema:
            type: object
            example: "A fake string"



    
